### ISSUE TITLE
Javascript Design Pattern needs improvement

### ISSUE THREAD

**Issue by ThomasBullock** [ThomasBullock/Mots-Movie-Browser#1]
## TODO

Javascript powering the site though working is "spaghetti code" and needs to be re-organised using recently learned better practices.
- engine.js 
- movie.js 
- list.js 

to be merged into a single javascript file using a objects
- Data 
- Controller  
- User Interface 

to structure the app.

**Comment by Loomernescent** [comment]
Master branch has been updated to include refactored js. 
There is still room for improvement with how the movie data is handled
